### PR TITLE
Move Eclipse project to Android Studio

### PR DESCRIPTION
**Pull request by Suvitruf**
I've included `classes.jar` to **lib** dir. This file users of this project should take from Unity3d directory, like mentioned in [Unity docs](http://docs.unity3d.com/Manual/PluginsForAndroid.html):

> To do this, first locate the classes.jar shipped with Unity Android. It is found in the installation folder (usually C:\Program Files\Unity\Editor\Data (on Windows) or /Applications/Unity (on Mac)) in a sub-folder called PlaybackEngines/AndroidPlayer/Variations/mono or il2cpp/Development or Release/Classes/

I think, better to mention it in read.me

P.S. to build **aar** file in Android Studio you should pick **assembleRelease** option in the right side:

assemblerelease

### CODE REVIEW

**Comment by Agasper** [comment]
Could you make a pull request into a ew brancn ?

**Comment by Suvitruf** [comment]
I can't create new branches in your project =\

**Comment by Agasper** [comment]
i did

**Comment by Suvitruf** [comment]
Ok, I've created new pr.

**Pull request closed without merging**
