### PR TITLE
Support notification actions, custom sounds, and Android 8.0 w/channels

### LINKED ISSUE #68: `UnityEngine.Application' does not contain a definition for `bundleIdentifier'
I am using Unity for Android development. When I play the Game on unity console it doesn't give any error but when i Build and run it on android it immediately gives this error Application.bundleIdentifier is giving error no definition is provided for it.
Kindly help me.

### PR DESCRIPTION
**Pull request by dgileadi**
I needed support for notification actions in both iOS and Android, and custom notification sounds. And I wanted to be able to run builds that target Oreo, with its required notification channels. This PR adds all those things.

I tried to keep the code as backwards-compatible as possible, so it shouldn't break anything.

Locally I changed the test project in Unity to add a button that calls `NotificationTest.OneTimeWithActions`, but I didn't commit the change because I'm using Unity v2017.2 and didn't want to force a Unity upgrade on everyone who uses this project.

This PR also incidentally fixes #68.

### CODE REVIEW

**Comment by Agasper** [comment]
Thanks for the work you've done. I hope you tested everything :)
Feel free to upgrade Unity project too, i'm trying to keep it fresh, but at the moment totally don't have enough time.

**Comment by dgileadi** [comment]
I did test it as much as I could, with my limited availability of devices and environments. There are a couple of things that could be improved—I didn't test icons for actions in Android, and in Android actions that have `.Foreground=false` doesn't delete the notification, for some reason. And if the Android app was stopped instead of running in the background, then selecting a notification action doesn't run the OnAction method.

**Comment by dgileadi** [comment]
Oh, and also—thanks for the awesome code to begin with!

**Comment by dgileadi** [comment]
Thanks, I will.

**Pull request merged**
